name: Backend Deployment
on:
  push:
    branches:
      - master
    paths:
      - "api/**"
jobs:
  build_and_deploy:
    if: github.repository_owner == 'tfkhdyt'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        working-directory: "./api"
        run: |
          docker login --username tfkhdyt --password ${{ secrets.DOCKER_PASS }}
          docker build -t tfkhdyt/gan-an-wo-api:latest .
          docker push tfkhdyt/gan-an-wo-api:latest
